name: Scrape AWS Docs

on:
  workflow_dispatch:      # you can also trigger manually anytime
  schedule:
    - cron: '0 * * * *'   # runs every hour on the hour

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14.6'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py
